apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  ports:
  - name: portmaping
    port: 9100
    protocol: TCP
    targetPort: 9100
    nodePort: 30007
  selector:
    app: node-exporter
  type: NodePort
